version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf       # NGINX 설정 파일
      - ./ssl:/etc/nginx/ssl                              # SSL 인증서 파일 경로
    networks:
      - the_monitor_network
    depends_on:
      - app

  app:
    image: ${DOCKER_USERNAME}/the_monitor:latest
    container_name: the_monitor-container
    env_file:
      - .env
    networks:
      - the_monitor_network
    expose:
      - "8080"

  redis:
    image: redis:7.0.11
    container_name: redis-server
    networks:
      - the_monitor_network
    ports:
      - "6379:6379"

networks:
  the_monitor_network:
    driver: bridge